---
# tasks file for linux packages
#
 - name: system packages | cli user utils in Debian
   become: yes
   apt:
     name: "{{ item }}"
     state: present 
   with_items: "{{ debian_packages }}"
   when: ansible_os_family ==  'Debian'

 - name: system packages | cli user utils in Redhat
   yum:
     name: "{{ item }}"
     state: present
   with_items: "{{ redhat_packages }}"
   when: ansible_os_family == 'RedHat'
